class Translator {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // Home Tab
      'home_authentic_flavor': 'AUTHENTIC FLAVOR',
      'home_heritage_recipes': 'Heritage Recipes\nfor Modern Palates',
      'home_shop_ishoma': 'Shop is in ISHOMA. Orders will be processed in ±15 minutes.',
      'home_shop_closed': 'Shop is CLOSED. You can only view the menu.',
      'home_closed_title': 'WARUNG CLOSED',
      'home_order_disabled': 'Ordering is currently disabled',
      
      // My Order Tab
      'order_my_order': 'My Order',
      'order_tracking_journey': 'Tracking your hand-crafted culinary journey',
      'order_no_orders': 'No orders yet',
      'order_history': 'Order History',
      'order_no_history': 'No previous orders found',
      'order_status_ready': 'Order Ready!',
      'order_status_validating': 'Validating Order',
      'order_status_preparing': 'Preparing',
      'order_placed_today': 'Placed today • Counter 4',
      'order_standard_prep': 'Standard Preparation',
      'order_check_status': 'Check Order',
      'order_cancelled': 'Cancelled',
      'order_completed': 'Completed',
      'order_rate_and_finish': 'Rate & Finish',
      'order_rating_question': 'How was your meal?',
      'order_rating_desc': 'Your feedback helps Mpo Lemez improve!',
      'order_rating_placeholder': 'Add a note (optional)...',
      'order_rating_later': 'Later',
      'order_rating_send': 'Send',
      'order_rating_thanks': 'Thank you for your rating!',
      
      // Profile Tab
      'profile_personal_info': 'Personal Information',
      'profile_notifications': 'Notifications',
      'profile_privacy': 'Privacy & Security',
      'profile_language': 'Language',
      'profile_sign_out': 'Sign Out',
      'profile_change_pic': 'Change Profile Picture',
      'profile_camera': 'Camera',
      'profile_gallery': 'Gallery',
      'profile_uploading': 'Uploading profile picture...',
      'profile_upload_success': 'Profile picture updated!',
      'profile_upload_fail': 'Failed to pick image',
      
      // Cart Screen
      'cart_your_order': 'Your Order',
      'cart_review_fresh': 'Review your fresh selections before checkout',
      'cart_empty': 'Your cart is empty',
      'cart_go_shopping': 'Go Shopping',
      'cart_no_substitutions': 'No substitutions',
      'cart_special_instructions': 'Special Instructions',
      'cart_subtotal': 'Subtotal',
      'cart_tax': 'Tax (10%)',
      'cart_total': 'Total Order',
      'cart_shop_closed': 'Shop is Closed',
      'cart_review_order': 'Review Order',
      
      // Order Summary
      'summary_title': 'Order Summary',
      'summary_subtitle': 'Review your items before we start preparing your meal.',
      'summary_your_items': 'Your Items',
      'summary_items_count': 'ITEMS',
      'summary_customizations': 'Customizations Added',
      'summary_qty': 'Qty',
      'summary_service_details': 'Service Details',
      'summary_dine_in': 'Dine In',
      'summary_take_away': 'Take Away',
      'summary_rsvp': 'RSVP',
      'summary_delivery': 'Delivery',
      'summary_rsvp_date': 'Reservation Date',
      'summary_rsvp_time': 'Arrival Time',
      'summary_rsvp_select': 'Select',
      'summary_rsvp_not_selected': 'Not selected',
      'summary_rsvp_invalid_time': 'Sorry, we only serve RSVP from 10:00 to 17:00.',
      'summary_delivery_location': 'Delivery Location',
      'summary_distance': 'Distance',
      'summary_shipping': 'Shipping',
      'summary_payment_method': 'Payment Method',
      'summary_pay_cash': 'Cash',
      'summary_pay_qris': 'QRIS',
      'summary_pay_bank': 'Bank Trf',
      'summary_pay_ewallet': 'E-Wallet',
      'summary_download_qris': 'Download QRIS',
      'summary_receipt': 'Receipt',
      'summary_grand_total': 'Grand Total',
      'summary_confirm_pay': 'Confirm & Pay',
      'summary_add_more': 'Add More Items',
      'summary_secure_payment': 'SECURE ENCRYPTED PAYMENT',
      'summary_upload_proof': 'Please upload payment proof first',
      'summary_order_confirmed': 'Order Confirmed!',
      'summary_success_desc': 'Your meal is being prepared with love and will be on its way shortly.',
      'summary_order_time_label': 'ORDER TIME',
      'summary_order_user_label': 'ORDER BY',
      'summary_go_home': 'Go to Home',
      'summary_track_order': 'Track My Order',
      
      // Categories
      'cat_all': 'All',
      'cat_main': 'Main Course',
      'cat_drinks': 'Drinks',
      'cat_snack': 'Snack',
      'cat_others': 'Others',
      'cat_veg': 'Vegetables',
      'cat_protein': 'Protein & Sides',
      'cat_condiments': 'Condiments',
      'cat_drinks_liquid': 'Drinks & Liquids',
      'cat_fruit': 'Fruit',
      'cat_addon': 'Add-ons',

      // Common
      'upload_proof_here': 'Upload proof here',
      'tap_to_select': 'Tap to select image',
      'fail_place_order': 'Failed to place order. Please try again.',
      'fail_upload_proof': 'Failed to upload proof',

      // Order Details
      'details_title': 'Order Details',
      'details_ready_pickup': 'Ready for Pickup',
      'details_status_log': 'Status Log',
      'details_order_completed': 'Order Successfully Finished!',
      'details_finish_btn': 'Finished Order',
      'dt_pending': 'Order Received',
      'dt_preparing': 'Your Order is Being Prepared',
      'dt_ready': 'Your Order is Ready',
      'dt_validating': 'Order Awaiting Validation',
      'dt_finished': 'Order Finished',
      'dt_just_now': 'Just Now',
      'pickup_location': 'PICKUP LOCATION',
      'delivery_location': 'DELIVERY LOCATION',
      'status_dine_in': 'Dine In',
      'status_take_away': 'Take Away',
      'status_delivery': 'Delivery',
      'status_rsvp': 'RSVP',
      'status_ready_delivery': 'Being Delivered',
      'dt_ready_delivery': 'Order on its way to your address',
      'details_no_address': 'Address not specified',
      'contact_card_title': 'Hubungi Kami',
      'contact_card_subtitle': 'Ada pertanyaan mengenai pesanan Anda?',
      'contact_whatsapp': 'Chat WhatsApp',
      'contact_call': 'Telepon Langsung',
      'contact_customer_title': 'Kontak Pelanggan',
      'contact_customer_subtitle': 'Hubungi pelanggan untuk koordinasi pengiriman.',
      'contact_no_phone': 'Nomor tidak tersedia',


      // Location Picker
      'loc_title': 'Select Delivery Location',
      'loc_searching': 'Searching for address...',
      'loc_not_found': 'Address not found',
      'loc_confirm': 'Confirm Location',

      // Edit Profile
      'profile_edit_success': 'Profile updated successfully!',
      'profile_edit_fail': 'Failed to update profile',
      'profile_detail_info': 'Detail Information',
      'profile_detail_desc': 'Keep your personal details up to date so we can serve you better.',
      'profile_full_name': 'Full Name',
      'profile_email': 'Email Address',
      'profile_phone': 'Phone Number',
      'profile_save_changes': 'Save Changes',

      // Notifications
      'notif_pref': 'Notification Preferences',
      'notif_desc': 'Stay updated with the latest news and your order status.',
      'notif_push': 'Push Notifications',
      'notif_push_desc': 'Real-time alerts for your orders',
      'notif_email': 'Email Notifications',
      'notif_email_desc': 'Get receipts and news via email',
      'notif_offers': 'Special Offers',
      'notif_offers_desc': 'Exclusive discounts and promos',

      // Privacy & Security
      'priv_mgmt': 'Security Management',
      'priv_desc': 'Protect your account with advanced security features.',
      'priv_change_pw': 'Change Password',
      'priv_change_pw_desc': 'Update your account password regularly',
      'priv_2fa': 'Two-Factor Authentication',
      'priv_2fa_desc': 'Add an extra layer of security',
      'priv_policy': 'Privacy Policy',
      'priv_policy_desc': 'Learn how we protect your data',
      'pw_current': 'Current Password',
      'pw_new': 'New Password',
      'pw_confirm': 'Confirm New Password',
      'pw_cancel': 'Cancel',
      'pw_update': 'Update',
      'pw_success': 'Password updated successfully!',

      // Navigation
      'nav_home': 'Home',
      'nav_order': 'My Order',
      'nav_profile': 'Profile',

      // Food Tags
      'tag_best_seller': 'Best Seller',
      'tag_new': 'New',
      'tag_out_of_stock': 'HABIS',
      'tag_out_of_stock_desc': 'Out of Stock',
      'toast_added_to_cart': 'added to cart',
      'home_items': 'items',
      'home_active': 'Active',
      'home_ready_status': 'Ready Status',
      'home_active_orders': 'Active Orders',
      'home_handcrafted': 'Hand-crafted favorite',
      'home_status_ready': 'READY',
      'home_status_sold_out': 'SOLD OUT',
      'home_status_open_title': 'Warung is Open',
      'home_status_ishoma_title': 'Warung is Ishoma',
      'home_status_closed_title': 'Warung is Closed',
      'home_status_open_sub': 'Taking orders for',
      'home_status_ishoma_sub': 'Pause for rest (12:00 - 13:00)',
      'home_status_closed_sub': 'No orders accepted currently',
      'home_notify_owner': 'NOTIFY OWNER',
      'home_low_inventory': 'Critical Inventory',
      'home_low_inventory_desc': 'The following ingredients are below minimum threshold.',
      'home_send_notif_owner': 'SEND NOTIFICATION TO OWNER',
      'home_report_sent': 'Stock report sent to Owner',
      'home_notif_sent': 'Notification sent to Owner Dashboard',
      'home_safe_stock': 'All stock is currently safe',
      'home_tables': 'tables',

      // Admin Home
      'admin_welcome': 'Welcome back, Staff',
      'admin_live_availability': 'Live Menu Availability',
      'admin_incoming_orders': 'Incoming Live Orders',
      'admin_no_orders': 'No orders right now',
      'admin_available': 'Available',
      'admin_out_of_stock': 'Out of Stock',
      'admin_add_menu': 'Add Menu',
      
      // Admin Stock
      'stock_ops': 'OPERATIONS',
      'stock_core_ingredients': 'Core Ingredients',
      'stock_manage_desc': 'Manage your raw ingredient inventory to ensure kitchen readiness.',
      'stock_in_stock': 'IN STOCK',
      'stock_out_of_stock': 'OUT OF STOCK',
      'stock_empty_title': 'Empty Ingredient Stock',
      'stock_empty_desc': 'Initialize your core ingredient stock now.',
      'stock_init_btn': 'INITIALIZE ALL INGREDIENTS',
      'stock_init_dialog_title': 'Bulk Stock Initialization',
      'stock_init_dialog_content': 'This will automatically add the default ingredients to the database. Continue?',
      'stock_init_processing': 'Processing initialization...',
      'stock_init_success': 'Initialization complete! Stock is now available.',
      'stock_items_count': 'Items',
      'stock_low_stock': 'LOW STOCK',

      // Admin Reports
      'admin_employee_id': 'Employee ID',
      'profile_account_settings': 'Account Settings',
      'report_overview': 'Operational Overview',
      'order_detail_title': 'Order #',
      'order_detail_update_status': 'Update Status',
      'order_detail_arrival': 'Arriving at',
      'summary_special_req': 'Special Request',
      'report_summary_today': 'Today\'s Summary',
      'report_summary_weekly': 'Weekly Summary',
      'report_summary_monthly': 'Monthly Summary',
      'report_ops_overview': 'Operational Overview',
      'report_period_day': 'Daily',
      'report_period_week': 'Weekly',
      'report_period_month': 'Monthly',
      'report_revenue': 'Total Revenue',
      'report_orders_handled': 'ORDERS HANDLED',
      'report_avg_service': 'AVG. SERVING',
      'report_tab_overview': 'Overview',
      'report_tab_items': 'Top Items',
      'report_tab_services': 'Services',
      'report_order_status': 'Order Status Summary',
      'report_others': 'Others',
      'report_last_transactions': 'Last Transactions',
      'report_view_all': 'View All',
      'report_no_data': 'No transactions yet',
      'report_no_data_items': 'No orders placed yet',
      'report_tip_title': 'Efficiency Tip',
      'report_tip_desc': 'Peak hours usually start at 12:00 PM. Ensure all prep stations are stocked by 11:30 AM to maintain service speed.',
      'report_most_ordered': 'Most Ordered Items',
      'report_sold_count': 'sold',
      'report_revenue_service': 'Revenue by Service Type',
      'report_rev_pct': 'of total revenue',
      'report_status_success': 'SUCCESS',
      'report_status_cancelled': 'CANCELLED',
      'report_all_transactions': 'All Transactions',
      'report_filter_all': 'All',
      'report_filter_success': 'Success',
      'report_filter_cancelled': 'Cancelled',
      'report_efficiency_tip': 'Efficiency Tip',
      'report_tip_content': 'Peak hours usually start at 12:00 PM. Ensure all prep stations are stocked by 11:30 AM to maintain service speed.',

      // Admin Profile
      'admin_shift_active': 'Shift Active',
      'admin_current_shift': 'CURRENT WORK SHIFT',
      'admin_rating': 'Monthly Rating',
      'admin_account_settings': 'Account Settings',
      'admin_logout_confirm_title': 'Logout',
      'admin_logout_confirm_content': 'Are you sure you want to logout?',
      'admin_change_pic_title': 'Change Admin Profile Photo',
      'admin_uploading_pic': 'Uploading Admin profile photo...',
      'admin_upload_success': 'Admin profile photo updated!',

      // Admin Forms
      'notif_settings_title': 'Notification Settings',
      'notif_manage_title': 'Manage Notifications',
      'notif_manage_desc': 'Choose the types of notifications you want to enable to stay updated with your outlet.',
      'notif_app_title': 'App Notifications',
      'notif_app_desc': 'Receive push notifications for new orders and stock updates.',
      'notif_daily_report_title': 'Daily Sales Report',
      'notif_daily_report_desc': 'Get a daily sales summary directly to the app or email.',
      'notif_system_update_title': 'System Updates',
      'notif_system_update_desc': 'Information about new features and system improvements for GadoGado POS.',
      'notif_sync_desc': 'These settings will be synced across all other Admin devices.',
      'priv_account_security': 'Account Security',
      'priv_pw_desc': 'Ensure your new password is strong and do not share it with anyone.',
      'priv_err_empty': 'Please fill in all fields.',
      'priv_err_mismatch': 'Password confirmation does not match!',
      'priv_success': 'Password successfully updated!',
      'priv_error': 'Failed to update password',
      'priv_current_pw': 'Current Password',
      'priv_new_pw': 'New Password',
      'priv_confirm_new_pw': 'Confirm New Password',
      'priv_show_pw': 'Show Password',
      'priv_hide_pw': 'Hide Password',
      'priv_btn_update': 'Update Password',
      'stock_add_title': 'Add New Item',
      'stock_add_desc': 'Enter details to update your digital inventory.',
      'stock_btn_save': 'Save Item',
      'stock_pro_tip': 'Pro-tip: Setting realistic minimum stock levels helps you avoid "Out of Stock" scenarios and keeps your customers happy!',
      'stock_update_title': 'Update Stock Item',
      'stock_update_desc': 'Update inventory details to ensure smooth kitchen operations.',
      'stock_label_min_threshold': 'MINIMUM STOCK ALERT',
      'stock_hint_min_threshold': 'Warning threshold',
      'stock_threshold_desc': 'We will notify you if stock falls below this level.',
      'stock_threshold_success': 'threshold updated!',
      'stock_tip_desc': 'Note: Ensure the entered stock amount matches the physical quantity available in the kitchen for data accuracy.',
      'menu_add_title': 'Add New Menu',
      'menu_add_desc': 'Fill in the details below to add a new item to the customer\'s real-time menu.',
      'menu_label_name': 'MENU NAME',
      'menu_hint_name': 'e.g., Special Fried Rice',
      'menu_label_desc': 'DESCRIPTION',
      'menu_hint_desc': 'Describe the deliciousness of this menu...',
      'menu_label_price': 'PRICE (RP)',
      'menu_label_category': 'CATEGORY',
      'menu_label_image': 'CHOOSE MENU IMAGE',
      'menu_hint_image': 'Take a Photo from Camera or Gallery',
      'menu_err_name_price': 'Please fill in Name and Price.',
      'menu_err_image': 'Please select a menu photo first.',
      'menu_status_upload': 'Uploading image...',
      'menu_status_save': 'Saving menu data...',
      'menu_success_cloud': 'successfully added to Cloud!',
      'menu_btn_save': 'Save Menu',
      'menu_image_source': 'Choose Image Source',
      'menu_source_camera': 'Camera',
      'menu_source_gallery': 'Gallery',
      'menu_delete_success': 'successfully deleted',

      'ing_update_title': 'Update Item Stock',
      'ing_update_desc': 'Update inventory details to ensure smooth kitchen operations.',
      'ing_field_name': 'ITEM NAME',
      'ing_field_unit': 'UNIT',
      'ing_field_min_stock': 'MINIMUM STOCK ALERT',
      'ing_min_stock_desc': 'We will notify you if stock falls below this level.',
      'ing_btn_save': 'Save Changes',
      'ing_btn_delete': 'Remove From Inventory',
      'ing_delete_confirm_title': 'Delete Item?',
      'ing_delete_confirm_content': 'Are you sure you want to remove this item from the inventory list?',
      'ing_tip_content': 'Note: Ensure the entered stock amount matches the physical quantity available in the kitchen for data accuracy.',

      // Common Admin
      'nav_stock': 'Stock',
      'nav_reports': 'Reports',
      'status_open': 'OPEN',
      'status_closed': 'CLOSED',
      'status_ishoma': 'ISHOMA',
      'update_status': 'Update Status',
      'select_language': 'Select Language',
      'lang_changed_to': 'Language changed to',
      'role_admin': 'Admin',
      'role_customer': 'Customer',
      'status_pending': 'Pending',
      'status_preparing': 'Preparing',
      'status_ready': 'Ready',
      'status_completed': 'Completed',
      'status_finished': 'Finished',
      'status_cancelled': 'Cancelled',
      'admin_brand_slogan': 'THE ARTISAN\'S COUNTER',
      'admin_build_version': 'v2.4.0-stable build',
      'admin_shift_morning': 'Morning Freshness Shift',
      'admin_shift_counter': 'Counter A',
      'admin_shift_time': '08:00 AM – 04:00 PM',
      'admin_rating_label': 'Rating',
      'admin_service_speed': '8.5m',
      'admin_ready_status': '85%',
      'admin_status_updated': 'Status updated to',
    },
    'id': {
      // Home Tab
      'home_authentic_flavor': 'RASA AUTENTIK',
      'home_heritage_recipes': 'Resep Warisan\nuntuk Lidah Modern',
      'home_shop_ishoma': 'Warung sedang ISHOMA. Pesanan akan diproses dalam ±15 menit.',
      'home_shop_closed': 'Warung sedang TUTUP. Anda hanya dapat melihat menu saat ini.',
      'home_closed_title': 'WARUNG TUTUP',
      'home_order_disabled': 'Pemesanan sedang dinonaktifkan',
      
      // My Order Tab
      'order_my_order': 'Pesanan Saya',
      'order_tracking_journey': 'Melacak perjalanan kuliner buatan tangan Anda',
      'order_no_orders': 'Belum ada pesanan',
      'order_history': 'Riwayat Pesanan',
      'order_no_history': 'Tidak ada riwayat pesanan ditemukan',
      'order_status_ready': 'Pesanan Siap!',
      'order_status_validating': 'Validasi Pesanan',
      'order_status_preparing': 'Sedang Diproses',
      'order_placed_today': 'Dipesan hari ini • Loket 4',
      'order_standard_prep': 'Persiapan Standar',
      'order_check_status': 'Cek Pesanan',
      'order_cancelled': 'Dibatalkan',
      'order_completed': 'Selesai',
      'order_rate_and_finish': 'Beri Rating & Selesaikan',
      'order_rating_question': 'Bagaimana makanan Anda?',
      'order_rating_desc': 'Masukan Anda membantu Mpo Lemez berkembang!',
      'order_rating_placeholder': 'Tambahkan catatan (opsional)...',
      'order_rating_later': 'Nanti Saja',
      'order_rating_send': 'Kirim',
      'order_rating_thanks': 'Terima kasih atas penilaian Anda!',
      
      // Profile Tab
      'profile_personal_info': 'Informasi Pribadi',
      'profile_notifications': 'Notifikasi',
      'profile_privacy': 'Privasi & Keamanan',
      'profile_language': 'Bahasa',
      'profile_sign_out': 'Keluar',
      'profile_change_pic': 'Ganti Foto Profil',
      'profile_camera': 'Kamera',
      'profile_gallery': 'Galeri',
      'profile_uploading': 'Mengunggah foto profil...',
      'profile_upload_success': 'Foto profil berhasil diperbarui!',
      'profile_upload_fail': 'Gagal mengambil gambar',
      
      // Cart Screen
      'cart_your_order': 'Pesanan Anda',
      'cart_review_fresh': 'Tinjau pilihan segar Anda sebelum checkout',
      'cart_empty': 'Keranjang belanja Anda kosong',
      'cart_go_shopping': 'Ayo Belanja',
      'cart_no_substitutions': 'Tanpa permintaan khusus',
      'cart_special_instructions': 'Instruksi Khusus',
      'cart_subtotal': 'Subtotal',
      'cart_tax': 'Pajak (10%)',
      'cart_total': 'Total Pesanan',
      'cart_shop_closed': 'Warung Sedang Tutup',
      'cart_review_order': 'Tinjau Pesanan',
      
      // Order Summary
      'summary_title': 'Ringkasan Pesanan',
      'summary_subtitle': 'Tinjau item Anda sebelum kami mulai menyiapkan makanan Anda.',
      'summary_your_items': 'Item Anda',
      'summary_items_count': 'ITEM',
      'summary_customizations': 'Modifikasi Ditambahkan',
      'summary_qty': 'Jumlah',
      'summary_service_details': 'Detail Layanan',
      'summary_dine_in': 'Makan di Tempat',
      'summary_take_away': 'Bawa Pulang',
      'summary_rsvp': 'Reservasi',
      'summary_delivery': 'Pengiriman',
      'summary_rsvp_date': 'Tanggal Reservasi',
      'summary_rsvp_time': 'Jam Kedatangan',
      'summary_rsvp_select': 'Pilih',
      'summary_rsvp_not_selected': 'Belum dipilih',
      'summary_rsvp_invalid_time': 'Maaf, kami hanya melayani RSVP jam 10:00 sampai 17:00.',
      'summary_delivery_location': 'Lokasi Pengiriman',
      'summary_distance': 'Jarak',
      'summary_shipping': 'Ongkir',
      'summary_payment_method': 'Metode Pembayaran',
      'summary_pay_cash': 'Tunai',
      'summary_pay_qris': 'QRIS',
      'summary_pay_bank': 'Trf Bank',
      'summary_pay_ewallet': 'E-Wallet',
      'summary_download_qris': 'Download QRIS',
      'summary_receipt': 'Struk',
      'summary_grand_total': 'Total Keseluruhan',
      'summary_confirm_pay': 'Konfirmasi & Bayar',
      'summary_add_more': 'Tambah Item Lagi',
      'summary_secure_payment': 'PEMBAYARAN TERENKRIPSI AMAN',
      'summary_upload_proof': 'Silakan upload bukti pembayaran terlebih dahulu',
      'summary_order_confirmed': 'Pesanan Dikonfirmasi!',
      'summary_success_desc': 'Makanan Anda sedang disiapkan dengan cinta dan akan segera dikirim.',
      'summary_order_time_label': 'JAM PESAN',
      'summary_order_user_label': 'PEMESAN',
      'summary_go_home': 'Ke Beranda',
      'summary_track_order': 'Lacak Pesanan Saya',
      
      // Categories
      'cat_all': 'Semua',
      'cat_main': 'Makanan Utama',
      'cat_drinks': 'Minuman',
      'cat_snack': 'Camilan',
      'cat_others': 'Lainnya',
      'cat_veg': 'Sayuran',
      'cat_protein': 'Protein & Pelengkap',
      'cat_condiments': 'Bumbu',
      'cat_drinks_liquid': 'Minuman / Cairan',
      'cat_fruit': 'Buah',
      'cat_addon': 'Pelengkap',
      
      // Common
      'upload_proof_here': 'Upload bukti di sini',
      'tap_to_select': 'Ketuk untuk pilih gambar',
      'fail_place_order': 'Gagal membuat pesanan. Silakan coba lagi.',
      'fail_upload_proof': 'Gagal mengunggah bukti',

      // Order Details
      'details_title': 'Detail Pesanan',
      'details_ready_pickup': 'Siap Diambil',
      'details_status_log': 'Riwayat Status',
      'details_order_completed': 'Pesanan Berhasil Diselesaikan!',
      'details_finish_btn': 'Pesanan Selesai',
      'dt_pending': 'Pesanan Diterima',
      'dt_preparing': 'Pesanan-mu Sedang Dibuat',
      'dt_ready': 'Pesanan-Mu Sudah Siap',
      'dt_validating': 'Pesanan Menunggu Validasi',
      'dt_finished': 'Pesanan Selesai',
      'dt_just_now': 'Baru Saja',
      'pickup_location': 'LOKASI PENGAMBILAN',
      'delivery_location': 'LOKASI PENGIRIMAN',
      'status_dine_in': 'Makan di Tempat',
      'status_take_away': 'Ambil Sendiri',
      'status_delivery': 'Pengantaran',
      'status_rsvp': 'Reservasi',
      'status_ready_delivery': 'Dalam Pengantaran',
      'dt_ready_delivery': 'Pesanan Dalam Perjalanan Ke Alamat-Mu',
      'details_no_address': 'Alamat tidak tersedia',
      'contact_card_title': 'Hubungi Kami',
      'contact_card_subtitle': 'Ada pertanyaan mengenai pesanan Anda?',
      'contact_whatsapp': 'Chat WhatsApp',
      'contact_call': 'Telepon Langsung',
      'contact_customer_title': 'Kontak Pelanggan',
      'contact_customer_subtitle': 'Hubungi pelanggan untuk koordinasi pengiriman.',
      'contact_no_phone': 'Nomor tidak tersedia',


      // Location Picker
      'loc_title': 'Pilih Lokasi Pengiriman',
      'loc_searching': 'Mencari alamat...',
      'loc_not_found': 'Alamat tidak ditemukan',
      'loc_confirm': 'Konfirmasi Lokasi',

      // Edit Profile
      'profile_edit_success': 'Profil berhasil diperbarui!',
      'profile_edit_fail': 'Gagal memperbarui profil',
      'profile_detail_info': 'Informasi Detail',
      'profile_detail_desc': 'Jaga data pribadi Anda tetap mutakhir agar kami dapat melayani Anda lebih baik.',
      'profile_full_name': 'Nama Lengkap',
      'profile_email': 'Alamat Email',
      'profile_phone': 'Nomor Telepon',
      'profile_save_changes': 'Simpan Perubahan',

      // Notifications
      'notif_pref': 'Preferensi Notifikasi',
      'notif_desc': 'Tetap terupdate dengan berita terbaru dan status pesanan Anda.',
      'notif_push': 'Notifikasi Push',
      'notif_push_desc': 'Peringatan waktu nyata untuk pesanan Anda',
      'notif_email': 'Notifikasi Email',
      'notif_email_desc': 'Dapatkan struk dan berita melalui email',
      'notif_offers': 'Penawaran Khusus',
      'notif_offers_desc': 'Diskon dan promo eksklusif',

      // Privacy & Security
      'priv_mgmt': 'Manajemen Keamanan',
      'priv_desc': 'Lindungi akun Anda dengan fitur keamanan tingkat lanjut.',
      'priv_change_pw': 'Ganti Kata Sandi',
      'priv_change_pw_desc': 'Perbarui kata sandi akun Anda secara berkala',
      'priv_2fa': 'Autentikasi Dua Faktor',
      'priv_2fa_desc': 'Tambahkan lapisan keamanan ekstra',
      'priv_policy': 'Kebijakan Privasi',
      'priv_policy_desc': 'Pelajari bagaimana kami melindungi data Anda',
      'pw_current': 'Kata Sandi Saat Ini',
      'pw_new': 'Kata Sandi Baru',
      'pw_confirm': 'Konfirmasi Kata Sandi Baru',
      'pw_cancel': 'Batal',
      'pw_update': 'Perbarui',
      'pw_success': 'Kata Sandi berhasil diperbarui!',

      // Navigation
      'nav_home': 'Beranda',
      'nav_order': 'Pesanan Saya',
      'nav_profile': 'Profil',

      // Food Tags
      'tag_best_seller': 'Terlaris',
      'tag_new': 'Baru',
      'tag_out_of_stock': 'HABIS',
      'tag_out_of_stock_desc': 'Stok Habis',
      'toast_added_to_cart': 'ditambahkan ke keranjang',
      'home_items': 'item',
      'home_active': 'Aktif',
      'home_ready_status': 'Status Siap',
      'home_active_orders': 'Pesanan Aktif',
      'home_handcrafted': 'Favorit buatan tangan',
      'home_status_ready': 'SIAP',
      'home_status_sold_out': 'HABIS',
      'home_status_open_title': 'Warung Buka',
      'home_status_ishoma_title': 'Warung Ishoma',
      'home_status_closed_title': 'Warung Tutup',
      'home_status_open_sub': 'Menerima pesanan untuk',
      'home_status_ishoma_sub': 'Istirahat / Sholat (12:00 - 13:00)',
      'home_status_closed_sub': 'Tidak menerima pesanan saat ini',
      'home_notify_owner': 'BERITAHU OWNER',
      'home_low_inventory': 'Inventaris Kritis',
      'home_low_inventory_desc': 'Bahan-bahan berikut sudah di bawah ambang batas minimum.',
      'home_send_notif_owner': 'KIRIM NOTIFIKASI KE OWNER',
      'home_report_sent': 'Laporan stok dikirim ke Owner',
      'home_notif_sent': 'Notifikasi Terkirim ke Dashboard Owner',
      'home_safe_stock': 'Semua stok saat ini aman',
      'home_tables': 'meja',

      // Admin Home
      'admin_welcome': 'Selamat datang kembali, Staff',
      'admin_live_availability': 'Ketersediaan Menu Live',
      'admin_incoming_orders': 'Pesanan Live Masuk',
      'admin_no_orders': 'Tidak ada pesanan saat ini',
      'admin_available': 'Tersedia',
      'admin_out_of_stock': 'Stok Habis',
      'admin_add_menu': 'Tambah Menu',

      // Admin Stock
      'stock_ops': 'OPERASIONAL',
      'stock_core_ingredients': 'Bahan Pokok',
      'stock_manage_desc': 'Kelola inventaris bahan baku Anda untuk memastikan kesiapan dapur.',
      'stock_in_stock': 'STOK ADA',
      'stock_out_of_stock': 'STOK HABIS',
      'stock_empty_title': 'Stok Bahan Kosong',
      'stock_empty_desc': 'Inisialisasi stok bahan pokok Anda sekarang.',
      'stock_init_btn': 'INISIALISASI SEMUA BAHAN',
      'stock_init_dialog_title': 'Inisialisasi Stok Massal',
      'stock_init_dialog_content': 'Ini akan menambahkan bahan baku default ke database secara otomatis. Lanjutkan?',
      'stock_init_processing': 'Memproses inisialisasi...',
      'stock_init_success': 'Inisialisasi selesai! Stok bahan baku kini tersedia.',
      'stock_items_count': 'Item',
      'stock_low_stock': 'STOK MENIPIS',

      // Admin Reports
      'order_detail_title': 'Pesanan #',
      'order_detail_update_status': 'Update Status',
      'order_detail_arrival': 'Tiba pukul',
      'summary_special_req': 'Permintaan Khusus',
      'report_summary_today': 'Ringkasan Hari Ini',
      'report_summary_weekly': 'Ringkasan Mingguan',
      'report_summary_monthly': 'Ringkasan Bulanan',
      'admin_employee_id': 'ID Karyawan',
      'profile_account_settings': 'Pengaturan Akun',
      'report_overview': 'Ikhtisar Operasional',
      'report_period_day': 'Harian',
      'report_period_week': 'Mingguan',
      'report_period_month': 'Bulanan',
      'report_revenue': 'Total Pendapatan',
      'report_orders_handled': 'PESANAN DIPROSES',
      'report_avg_service': 'RATA-RATA LAYANAN',
      'report_tab_overview': 'Ikhtisar',
      'report_tab_items': 'Menu Terlaris',
      'report_tab_services': 'Layanan',
      'report_order_status': 'Ringkasan Status Pesanan',
      'report_others': 'Lainnya',
      'report_last_transactions': 'Transaksi Terakhir',
      'report_view_all': 'Lihat Semua',
      'report_sold': 'terjual',
      'report_rev_service': 'Pendapatan Berdasarkan Tipe Layanan',
      'report_of_total': 'dari total pendapatan',
      'report_filter_all': 'Semua',
      'report_filter_success': 'Berhasil',
      'report_filter_cancelled': 'Dibatalkan',
      'report_all_transactions': 'Seluruh Transaksi',

      // Admin Profile
      'admin_shift_active': 'Shift Aktif',
      'admin_current_shift': 'SHIFT KERJA SAAT INI',
      'admin_rating': 'Rating Bulanan',
      'admin_account_settings': 'Pengaturan Akun',
      'admin_logout_confirm_title': 'Logout',
      'admin_logout_confirm_content': 'Apakah Anda yakin ingin keluar?',
      'admin_change_pic_title': 'Ganti Foto Profil Admin',
      'admin_uploading_pic': 'Mengunggah foto profil Admin...',
      'admin_upload_success': 'Foto profil Admin diperbarui!',

      // Admin Forms
      'notif_settings_title': 'Pengaturan Notifikasi',
      'notif_manage_title': 'Kelola Pemberitahuan',
      'notif_manage_desc': 'Pilih jenis pemberitahuan yang ingin Anda aktifkan untuk tetap update dengan outlet Anda.',
      'notif_app_title': 'Notifikasi Aplikasi',
      'notif_app_desc': 'Terima pemberitahuan push untuk pesanan baru dan update stok.',
      'notif_daily_report_title': 'Laporan Penjualan Harian',
      'notif_daily_report_desc': 'Dapatkan rangkuman penjualan harian langsung ke aplikasi atau email.',
      'notif_system_update_title': 'Update Sistem',
      'notif_system_update_desc': 'Informasi mengenai fitur baru dan perbaikan sistem GadoGado POS.',
      'notif_sync_desc': 'Pengaturan ini akan disinkronkan di semua perangkat Admin lainnya.',
      'priv_account_security': 'Keamanan Akun',
      'priv_pw_desc': 'Pastikan password baru Anda kuat dan jangan beritahukan kepada siapapun.',
      'priv_err_empty': 'Silakan isi seluruh kolom.',
      'priv_err_mismatch': 'Konfirmasi password tidak cocok!',
      'priv_success': 'Password berhasil diperbarui!',
      'priv_error': 'Gagal memperbarui password',
      'priv_current_pw': 'Password Saat Ini',
      'priv_new_pw': 'Password Baru',
      'priv_confirm_new_pw': 'Konfirmasi Password Baru',
      'priv_show_pw': 'Tampilkan Password',
      'priv_hide_pw': 'Sembunyikan Password',
      'priv_btn_update': 'Update Password',
      'stock_add_title': 'Tambah Barang Baru',
      'stock_add_desc': 'Masukkan detail untuk memperbarui inventaris digital Anda.',
      'stock_btn_save': 'Simpan Barang',
      'stock_pro_tip': 'Tips pro: Menetapkan level stok minimum yang realistis membantu Anda menghindari skenario "Stok Habis" dan menjaga pelanggan Anda tetap senang!',
      'stock_update_title': 'Update Stok Barang',
      'stock_update_desc': 'Perbarui detail inventaris untuk memastikan operasional dapur tetap lancar.',
      'stock_label_min_threshold': 'PERINGATAN STOK MINIMUM',
      'stock_hint_min_threshold': 'Ambang batas peringatan',
      'stock_threshold_desc': 'Kami akan memberi tahu Anda jika stok turun di bawah level ini.',
      'stock_threshold_success': 'threshold berhasil diperbarui!',
      'stock_tip_desc': 'Catatan: Pastikan jumlah stok yang dimasukkan sesuai dengan kuantitas fisik yang tersedia di dapur untuk akurasi data.',
      'menu_add_title': 'Tambah Menu Baru',
      'menu_add_desc': 'Isi detail di bawah untuk menambahkan item baru ke menu real-time pelanggan.',
      'menu_label_name': 'NAMA MENU',
      'menu_hint_name': 'misal: Nasi Goreng Spesial',
      'menu_label_desc': 'DESKRIPSI',
      'menu_hint_desc': 'Jelaskan kelezatan menu ini...',
      'menu_label_price': 'HARGA (RP)',
      'menu_label_category': 'KATEGORI',
      'menu_label_image': 'PILIH GAMBAR MENU',
      'menu_hint_image': 'Ambil Foto dari Kamera atau Galeri',
      'menu_err_name_price': 'Harap isi Nama dan Harga.',
      'menu_err_image': 'Harap pilih foto menu terlebih dahulu.',
      'menu_status_upload': 'Mengunggah gambar...',
      'menu_status_save': 'Menyimpan data menu...',
      'menu_success_cloud': 'berhasil ditambahkan ke Cloud!',
      'menu_btn_save': 'Simpan Menu',
      'menu_image_source': 'Pilih Sumber Gambar',
      'menu_source_camera': 'Kamera',
      'menu_source_gallery': 'Galeri',
      'menu_delete_success': 'berhasil dihapus',

      'ing_update_title': 'Update Stok Barang',
      'ing_update_desc': 'Perbarui detail inventaris untuk memastikan operasional dapur tetap lancar.',
      'ing_field_name': 'NAMA BARANG',
      'ing_field_unit': 'SATUAN',
      'ing_field_min_stock': 'PERINGATAN STOK MINIMUM',
      'ing_min_stock_desc': 'Kami akan memberi tahu Anda jika stok turun di bawah level ini.',
      'ing_btn_save': 'Simpan Perubahan',
      'ing_btn_delete': 'Hapus Dari Inventaris',
      'ing_delete_confirm_title': 'Hapus Barang?',
      'ing_delete_confirm_content': 'Apakah Anda yakin ingin menghapus barang ini dari daftar inventaris?',
      'ing_tip_content': 'Catatan: Pastikan jumlah stok yang dimasukkan sesuai dengan kuantitas fisik yang tersedia di dapur untuk akurasi data.',

      // Common Admin
      'nav_stock': 'Stok',
      'nav_reports': 'Laporan',
      'status_open': 'BUKA',
      'status_closed': 'TUTUP',
      'status_ishoma': 'ISHOMA',
      'update_status': 'Update Status',
      'select_language': 'Pilih Bahasa',
      'lang_changed_to': 'Bahasa diubah ke',
      'status_pending': 'Menunggu',
      'status_preparing': 'Sedang Diproses',
      'status_ready': 'Siap Disajikan',
      'status_completed': 'Selesai',
      'status_finished': 'Selesai (Dibayar)',
      'status_cancelled': 'Dibatalkan',
      'admin_brand_slogan': 'KONTER SANG PENGRAJIN',
      'admin_build_version': 'v2.4.0-versi stabil',
      'admin_shift_morning': 'Shift Pagi Segar',
      'admin_shift_counter': 'Konter A',
      'admin_shift_time': '08:00 – 16:00',
      'admin_rating_label': 'Peringkat',
      'admin_service_speed': '8.5m',
      'admin_ready_status': '85%',
      'admin_status_updated': 'Status diperbarui menjadi',
      'role_admin': 'Admin',
      'role_customer': 'Pelanggan',
    },
  };

  static String translate(String key, String lang) {
    if (!_translations.containsKey(lang)) return key;
    return _translations[lang]![key] ?? key;
  }

  static String categoryTranslate(String category, String lang) {
    // Mapping from constants to keys
    switch (category) {
      case 'All': return translate('cat_all', lang);
      case 'Makanan Utama': return translate('cat_main', lang);
      case 'Drinks': return translate('cat_drinks', lang);
      case 'Snack': return translate('cat_snack', lang);
      case 'Sayuran': return translate('cat_veg', lang);
      case 'Protein / Pelengkap': return translate('cat_protein', lang);
      case 'Bumbu': return translate('cat_condiments', lang);
      case 'Minuman / Cairan': return translate('cat_drinks_liquid', lang);
      case 'Buah': return translate('cat_fruit', lang);
      case 'Pelengkap': return translate('cat_addon', lang);
      case 'Lainnya': return translate('cat_others', lang);
      case 'Others': return translate('cat_others', lang);
      default: return category;
    }
  }
}
